Resources:
  KephaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      Tags:
        - Key: Name
          Value: KephaVPC

  KephaIGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: KephaIGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref KephaVPC
      InternetGatewayId: !Ref KephaIGW

  KephaPublicSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref KephaVPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: us-east-1a   # Update with the desired availability zone
      Tags:
        - Key: Name
          Value: kephaPublicSubnet

  KephaRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref KephaVPC
      Tags:
        - Key: Name
          Value: KephaRT

  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
      RouteTableId: !Ref KephaRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref KephaIGW

  AssociateRouteTable:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId: !Ref KephaPublicSubnet
      RouteTableId: !Ref KephaRT

  KephaPublicSubnetNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !Ref KephaVPC
      Tags:
        - Key: Name
          Value: KephaPublicSubnetNetworkAcl

  InboundHTTPRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref KephaPublicSubnetNetworkAcl
      RuleNumber: 100
      Protocol: 6   # TCP
      PortRange:
        From: 80
        To: 80
      Egress: false
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  InboundHTTPsRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref KephaPublicSubnetNetworkAcl
      RuleNumber: 110
      Protocol: 6   # TCP
      PortRange:
        From: 443
        To: 443
      Egress: false
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  OutboundHTTPRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref KephaPublicSubnetNetworkAcl
      RuleNumber: 100
      Protocol: 6   # TCP
      PortRange:
        From: 80
        To: 80
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  OutboundHTTPsRule:
    Type: AWS::EC2::NetworkAclEntry
    Properties:
      NetworkAclId: !Ref KephaPublicSubnetNetworkAcl
      RuleNumber: 110
      Protocol: 6   # TCP
      PortRange:
        From: 443
        To: 443
      Egress: true
      RuleAction: allow
      CidrBlock: 0.0.0.0/0

  AssociateNetworkAcl:
    Type: AWS::EC2::SubnetNetworkAclAssociation
    Properties:
      SubnetId: !Ref KephaPublicSubnet
      NetworkAclId: !Ref KephaPublicSubnetNetworkAcl